### PR TITLE
Open Pull to implement `phone-number` exercise

### PR DESCRIPTION
**Pull request by Dispader**
Per [the most excellent documentation](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track), I'm opening this Pull to call dibs and track an implementation of `phone-number` for Groovy.

### CODE REVIEW

**Comment by Dispader** [comment]
Let the throwing of the tomatoes begin!

**Comment by Dispader** [comment]
One note: I'm really* new to this, so I apologize.

I noticed some of the exercises in the tracks come with individual `README.md` files— is that something that I should add here?

**Comment by kytrinyx** [comment]
> One note: I'm really* new to this, so I apologize.

No need to apologize :heart: thanks so much for the contribution!

> I noticed some of the exercises in the tracks come with individual README.md files— is that something that I should add here?

Nope—we construct the README out of shared metadata.

OK, I've put a call out for some help reviewing this! Hang on tight :) :tada:

**Comment by kimdbarnes** [comment]
Ok, it's been a while since I wrote Groovy, but here are some comments:

My most significant comment is actually opposite of another commit Katrina already merged in for raindrops, which is ironic! (2e47b945c611b99da50821c708c59402ec8bdba3) The comment is that the tests might be improved if they were one assertion per test. The reason I say that is mostly from a Exercism user point of view. I would like to be able to see at a glance that I'm progressing through the tests. Seeing 2 passing, 6 failing (for example) is easier for me to see as I progress instead of one single test failing at different line numbers. It takes a lot more attention to detail for me to see that my failure moved up or down a line number instead of seeing numbers of tests fail. Plus, it gives you the ability to give each test a meaningful name. For example, you can name one to explicitly say that alpha characters are converted to '0' instead of letting the reader guess that. (Which implies don't call them 'test1', 'test2', etc :-) )

Another is really a question. Are the defaults on line 5 of Example.groovy necessary? What's the behavior if the matcher doesn't make all 3 matches? Consider if those questions spur any ideas for improvement.

"REGEX" constant could have a more expressive name.

Ok, I was really stretching there, but hope that helps!

**Comment by Dispader** [comment]
Sorry for the long delay in response, there.

The first comment is really interesting, and something that I've been struggling with: bref, I agree with you, but don't know how to split the difference in tradeoffs.  As I see it, the upsides of the straight-Groovy-assertion test file are:

* the tests seem to "read" for a Groovy newbie
  * the learner doesn't really have to understand test approaches
  * we're not introducing things like JUnit or Spock
  * we're also not including "@Grab"s for libraries, and don't need a Gradle build
* the tests run and pass-or-fail in order
  * the learner doesn't have to comment out something like "@Ignore" to get the next failing test
* the test output is really quite nice for the learner

The downsides, however:

* the learner gets no count of the number of tests passed-vs.-failed
  * especially when all tests are uncommented
* the learner doesn't get exposed to the lingua-franca test frameworks
* (and the biggie, IMHO, which you also point out) there are no human-readable test names
  * we don't need to go on about this, but it is *huge

Which are no small things, either of them.  So, I'm kind of at a loss— because we could:

* introduce the GroovyTestCase class
  * (plus) individual tests, native, pretty lightweight, still in Groovy
  * (minus) names are still method names, GroovyTestCase is largely unused in the wild, the outputs are less-than-readable
* introduce JUnit
  * (plus) individual tests; while not native, very in the wild (for Java), count of pass/fail
  * (minus) multiple Grabs needed to make the tests work, names are still method names, tests are in a non-Groovy language, and test failures are... well, "daunting" doesn't quite cover it (dozens of lines for every failure, given in line numbers, with no cues), require managing "@Ignore"
* introduce Spock
  * (plus) individual tests, human-readable test names (included in output), current lingua franca for Groovy tests (and state-of-the art for Java), very* readable outputs (with test names and visual matches for failures), count of pass/fail
  * (minus) introduces multiple Grabs, introduces a whole DSL to the learner (albeit largely Groovy-like), require managing "@Ignore"
* (variant) Gradle build wrapping the above
  * (plus) removes Grab requirements from all the above
  * (minus) adds yet another file (and technology)

So... uuf.

I like your other comments as well, but I'm focusing on the structure of the tests because I'm not quite certain how to move forward.  Any input would be muchly, muchly appreciated.

Hope this finds you very well, and thank you both so much for your attention to the Pull!

**Comment by kimdbarnes** [comment]
Hi,

I'm really enjoying the conversation! I don't feel like I should be playing gatekeeper on this commit, but as long as you want to discuss, I'm happy to.

I still feel pretty strongly that the tests should be broken up. Here are some more arguments for it:
* The learner can iterate in a different order than the existing tests are laid out. I actually see one of your upsides, "the tests run and pass-or-fail in order", as a downside. The order may make sense for your solution, but there are a lot of ways to solve it, and I like to think Exercism encourages experimentation, not a single right answer.

* (again) The tests can have meaningful names to help guide the learner. One reason I like meaningful names is that they answer "why?". It's one thing to say area code should return "123", but if there are any potentially confusing assertions, it's nice to be able to say why. For example, the "0000000000" default on invalid phone numbers could use a good "why".
  * I just looked at the xruby examples for the "0000000000" cases and found these test names:
    * test_invalid_when_9_digits
    * test_invalid_with_letters_in_place_of_numbers
    * test_invalid_when_11_digits
    * test_invalid_when_12_digits_and_first_is_1
    * test_invalid_when_10_digits_with_extra_letters
  * Those tell me a lot more about why I'm returning all 0's instead of just doing it because I'm told to. ;-)

* The tests can be broken up by the public methods they test (areaCode() vs. number() vs. toString()) which will be a little less confusing and allow the learner to focus on a specific method.

* I don't think introducing a standard testing framework is too much overhead for the learner, and by the time they get to this exercise, they will have become quite familiar with Junit. 

* I just reviewed all the other groovy Exercisms and with the exception of Raindrops, they all use Junit and one assertion per test. 

* Same goes for removing @ignore. They'll be very comfortable with it by now. Just another argument for consistency. But this is the most minor point, you could certainly change all the other tests to be consistent, but I think one assertion per test wins out for me.

Kim

**Comment by batemansw** [comment]
I agree that the test should follow the format for the other tests - one assertion per method and written using JUnit. If it helps, I compile the tests using the commandline groovyc compiler and I don't need any @Grab or imports for JUnit to work. This is with groovy 2.4.5

**Comment by Dispader** [comment]
@batemansw @kimdbarnes I stand corrected!  JUnit 4 classes do, indeed resolve in default Groovy 2.4 environments!

They do also give the nice summary

> JUnit 4 Runner, Tests: 3, Failures: 3, Time: 62

I'm still kinda struggling with [what the output gives a new learner](https://github.com/exercism/xgroovy/files/460238/HelloWorldTest.groovy-output.txt), but I can stew on this for a while.

[HelloWorldTest.groovy-output.txt](https://github.com/exercism/xgroovy/files/460238/HelloWorldTest.groovy-output.txt)

Thanks!

**Comment by Dispader** [comment]
I'm going to translate `PhoneNumberTest.groovy` to be a JUnit test class (or introduce a new file, so we can see them side-by-side), but for the moment I've implemented `PhoneNumberSpec.groovy` as a Spock specification.

It does give us the test summary

```
(~/Development/github/xgroovy/exercises/phone-number) groovy-add-phone-number {azazel}07:50pm] groovy PhoneNumberSpec.groovy 
JUnit 4 Runner, Tests: 1, Failures: 0, Time: 149
```

and allows for the gradual introduction of tests with `@Ignore`.

I think it has benefits over the JUnit equivalent in that the test outputs look a little friendlier for learners

```
(~/Development/github/xgroovy/exercises/phone-number) groovy-add-phone-number {azazel}07:50pm] groovy PhoneNumberSpec.groovy 
JUnit 4 Runner, Tests: 1, Failures: 1, Time: 164
Test Failure: a phone number is valid(PhoneNumberSpec)
Condition not satisfied:

new PhoneNumber('(123) 456-7890').number == '1234567890'
|                                 |      |
(123x) 456-7890                   |      false
                                  |      1 difference (90% similarity)
                                  |      123(x)4567890
                                  |      123(-)4567890
                                  123x4567890

        at PhoneNumberSpec.a phone number is valid(PhoneNumberSpec.groovy:7)

(~/Development/github/xgroovy/exercises/phone-number) groovy-add-phone-number {azazel}07:56pm]
```

including long, human-readable test names and no long-scrolling stack traces.  I also think the tests themselves also seem to read as a bit more idiomatically Groovy

```
    def 'a phone number is valid'() {
        expect: new PhoneNumber('(123) 456-7890').number == '1234567890'
    }
```

All that said, I think it's probably most worthwhile for me to see this option side-by-side with a JUnit implementation.

And one more thing I'll agree on: we probably shouldn't accept this Pull request.  Even if we're convinced that the Specification approach is better, I'd rather go back through the introductory tests and translate them.  IMHO the tests should probably help the learner by allowing them to develop an intuition for the tests— and I'm going to apologize for proposing the different test form in Pull #21 .

I really do believe we can improve the experience by improving the test output (at least by shortening the stack trace on JUnit outputs), but even if I do manage to convince you good folk— I think we'd probably do better going back to the introductory exercises and change the tests there for consistency.

**Comment by kimdbarnes** [comment]
Hey!

This is great, and huge kudos for the commitment to making this better!
I'm cool with Spock and the improved output. :-)

Good work!

**Comment by Dispader** [comment]
Very well— I've (at least cursorily) looked for options for squashing or limiting the stack trace output for JUnit, and I have to say that I'm becoming more convinced that retrofitting tests to be Spock specifications is more appealing to me.

If I could I ask for another (related) question— does anyone have a preference for naming the tests?  `<class>Spec` is more accurate; but would `<class>Test` be any less confusing for someone coming fresh to Groovy exercises?

**Comment by kimdbarnes** [comment]
I think <class>Spec, if it's in line with the convention of Spock tests, is better. IMO, it's more important for the learner to be exposed to the Groovy (and in this case, Spock) environment than to be consistent across languages within Exercism.

**Comment by Dispader** [comment]
So be it— I've started up the work in another branch: we've baked some time for discussion, so I've started up the work in another branch.  It'll probably be a bit before I'm happy enough with the test conversions to open for comment, but hopefully not too-too long.

**Comment by kytrinyx** [comment]
@Dispader Would you mind rebasing this against the upstream master, and fixing the conflict?

**Comment by Dispader** [comment]
@kytrinyx  Absolutely.  I'll also go back and make sure it meets the styles we have on `master`.

**Comment by Dispader** [comment]
@kytrinyx Okay, there doesn't seem to be any `x-common` canonical-data, the tests are in Specs, and the Pull should be rebased from master.

**Comment by kytrinyx** [comment]
Fabulous! Thanks so much @Dispader!

**Pull request merged**
