### PR TITLE
hello-world: (please comment) example proposal to add Gradle build(s)

### PR DESCRIPTION
**Pull request by Dispader**
When going through the exercises, I noticed there was no mechanism for pulling in (JUnit) dependencies or fixating Groovy versions.  This is in stark contrast to the `xjava` Exercism exercise set.

Since Gradle is the de-facto build tool in the Groovyverse, I thought I'd give a go at contributing a Gradle build to the project.

I'll file an experimental Pull request for comment (with apologies, since I don't know the proper way to test contributions).

I'd also like to translate the JUnit tests to the Spock framework, the output of which might be much easier on newcomers to Groovy (plus, the tests will be in a Groovy DSL!), which I could easily add as commits to this (or another) request.

Please comment, and let me know if I'm making mistakes in the Pull to exercises!

### CODE REVIEW

**Comment by kytrinyx** [comment]
For the contribution, I'd love to see _just_ the gradle stuff in a separate PR, with hello-world submitted in a separate PR. Check out this stuff in the contributing guide: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#git-basics it describes how we typically work using branches to be able to submit isolated pull requests, etc.

It shouldn't take a lot of work to check your master into a branch, `rebase -i` to remove hello world commits, and squash the gradle-stuff into a single commit, but if you're not familiar with git it can be pretty intimidating, so (a) create a new branch called backup with what is on your current master so you don't risk losing any work through git confusion, and (b) holler and we'll walk you through it.

@jtigger or @matthewmorgan would you have time to check the gradle-specific stuff here?

**Comment by matthewmorgan** [comment]
@jtigger is probably better qualified at this point for the gradle piece.  John?

**Comment by Dispader** [comment]
@kytrinyx Thanks much for the correction on pulling from a remote branch— also, I can completely get behind separating a Gradliziation Pull from a Spock-test pull.  Thanks so much!

I appreciate @matthewmorgan 's call-out for another opinion on the Gradle build (I have heavy concerns about the size added by including a Wrapper).  So, if no one minds, I'd like to keep this not-intended-for-merge Pull open for some feedback before creating any real suggested Pull.

**Comment by Dispader** [comment]
I've had some time to re-think this one— and I believe there's enough to change and isolate here which can be discussed in a narrower scope.

Thank you!  (And hopefully see you with a new Pull later.)

**Comment by kytrinyx** [comment]
Thanks @Dispader!

**Pull request closed without merging**
